### ISSUE TITLE
adding information about different data import functions explicitly by either base r or some package

### ISSUE THREAD

**Issue by amnahsiddiqa** [datacarpentry/genomics-r-intro#100]
I wanted to contribute in improving the material from episode "R Basics continued - factors and data frames".
It is just a small contribution if it helps.
 
"Importing tabular data into R" is a very good start for novices but  I think it would 
be helpful to have a short section which adds at least two clarifications:

1- When introducing read.csv(), it could be helpful to mention that read_csv() exists 
and is different. New learners often are reaching out and learning by themselves and might get 
confused when thy see different terms in different resources and it might be heplful to
give them a hint right away to be prepared to see different terms and their reason. I have read the issues
mentioning that you are transitioning to tidy verse, in that case too this clarification would be great to have.

 2- Although the arguments for read.csv have been covered fully in "Exercise: Review the arguments 
 of the read.csv() function", I think it could be a nice addition to add more clarification 
 to the data import functions in detail in base R right away such as: 

read.table(): a general function that can be used to 
read a file in table format. The data will be imported as a data frame.
read.csv(): for reading “comma separated value” files (“.csv”).
read.csv2(): variant used in countries that use a comma “,” as decimal point and a semicolon “;” as field separators.
read.delim(): for reading “tab-separated value” files (“.txt”). By default, point (“.”) is used as decimal points.
read.delim2(): for reading “tab-separated value” files (“.txt”). By default, comma (“,”) is used as decimal points.

The main arguments for all of them: 
file: the path to the file containing the data to be imported into R.
sep: the field separator character. “\t” is used for tab-delimited file.
header: logical value. If TRUE, read.table() assumes that your file has a header row, so row 1 is the name of each column. If that’s not the case, you can add the argument header = FALSE.
dec: the character used in the file for decimal points.

It is not necessary to cover all of this when teaching the lesson, but students often gain 
knowledge when going through the materials in their own time and these little extra 
pieces can help new learners a lot from one same place. As in the beginning they are not 
comfortable to do efficient search for right terms and functions as well.

**Comment by ytakemon** [comment]
This had been addressed in a recent pull request #96
