### ISSUE TITLE
05 Adding information of the context of ggplot2

### ISSUE THREAD

**Issue by chechoid** [datacarpentry/genomics-r-intro#106]
Is it possible to add an image of the layers that you can control with ggplot2 like this one?

[https://englelab.gatech.edu/useRguide/images/dataviz/ge_themes.png](https://englelab.gatech.edu/useRguide/images/dataviz/ge_themes.png)

My suggestion to the content is the following:

The layers you can control are this one:

* **Data**: The source of the data that you're going to visualize.
* **Aesthetics**: Are the aesthetics modification you'll make in the plot by mapping variables into it.
* **Geometry**: Is the shape that will take the plot (bars, lines, points, etc.).

These are the three essential layers to make a plot with `ggplot2`. The rest of the layers are:

* **Facets**: Allows you to make separete a plot into individual plots in order to clean the visualization.
* **Statistics**: Add a layer with of statistical analysis like a linear regression, or an average.
* **Coordinates**: Allows you to control the axis, its formats, range, etc..
* **Theme**: Modifies the style of a plot, like the background, colours, fonts, and many more.

**Comment by ytakemon** [comment]
@ahmedmoustafa

**Comment by naupaka** [comment]
Closing due to lesson reorganization
