### ISSUE TITLE
Improvements still needed for episodes 03 and 04

### ISSUE THREAD

**Issue by naupaka** [datacarpentry/genomics-r-intro#11]
Copied from #10 

### 03-basics-factors-dataframes.Rmd

Questions and suggestions for help:

* Related to point 2 above, I'm not convinced that the REF column is an appropriate variable to use for this example as I can't construct an easy example of reordering the factors without introducing new syntax. Any suggestions appreciated. (starting on line 256)
* I'm having some trouble constructing relevant examples of the math manipulation functions, as I don't know what most of these variables represent and what it makes sense to do with them mathematically. For example, I looked up QUAL and it is a log-scaled quality score, so taking a simple mean isn't appropriate. It would be nice to get some suggestions here from someone who has worked with vcf format before.
* I haven't yet updated the section on Excel.

### 04-dplyr.Rmd
Questions and suggestions for help:

* Some of the new examples and exercises use the QUAL and DP columns. I've based my explanations of those variables on the Broad Institute documentation, but I would appreciate someone double checking my explanations as I'm not familiar with this file format.
* The examples in the "Split-apply-combine data analysis and the summarize() function" section were difficult to convert to this dataset. I could use some help coming up with good examples there.
* This episode needs more exercises.

**Comment by ErinBecker** [comment]
To add to this: PR https://github.com/carpentrieslab/genomics-r-intro/pull/10 also includes some incorporation of tidy vcf output into the ggplot episode, but I was finding that episode very challenging to adapt due to my lack of previous experience with vcf format. Improvements to that episode would be incredibly appreciated!

**Comment by JasonJWilliamsNY** [comment]
This issue is now made obsolete by the examples used in the current versions of this lesson.
