### ISSUE TITLE
05-data-visualization: i) suggestion of a tool for "melting" a dataframe to the 'long' format; ii) citing more examples of geom_

### ISSUE THREAD

**Issue by eltonjrv** [datacarpentry/genomics-r-intro#114]
Please delete the text below before submitting your contribution. 

Howdy folks,
First of all, congrats for that effort on creating this quite nice 'alpha' version of this brand new R for genomics workshop.  
Please find my comments/suggestions below:
i) On the "Plotting with ggplot2"  2nd paragraph, perhaps it might be worthwhile adding an addendum (or a link for further consultation after class) about how to transform  a regular table into  this 'long' ggplot-friendly dataframe format using the "melt"function from the "reshape2" package (https://www.geeksforgeeks.org/melting-and-casting-in-r-programming/). As a biologist, I remember when I first started with R (and didn't know the melt function) struggling to transform tables using either bash or PERL.
ii) Regarding "geom_" examples, I understand that you reasonably cited the ones that will be addressed in the lesson.
* `geom_point()` for scatter plots, dot plots, etc.
* `geom_boxplot()` for, well, boxplots!
* `geom_line()` for trend lines, time series, etc.
 However, again thinking as a biologist, I think that the audience will enjoying knowing other possibilities for fancy charts they usually see in papers. So, another code box could be open with an above text like the following "Not used today, but quite useful and possible with ggplot2".
* `geom_density()` for histograms.
* `geom_violin()` for violin plots.
* `geom_jitter()` for stripcharts.
* `geom_tile()` for heatmaps.

I hope you guys find these suggestions useful.
Thanks,
Best,
Elton
---

**Comment by ytakemon** [comment]
Hi @eltonjrv, 

Thanks for the suggestions. We've recently updated the dplyr/tidyverse lesson (pull #108) to incorporate `pivot_longer()` and `pivot_wider()` which should address the reshaping suggestion you had while keeping to our tidyerverse format.  

As for the ggplot lessons perhaps @ahmedmoustafa could take a look at that.
