### ISSUE TITLE
Definition of "$" not addressed in episode 3

### ISSUE THREAD

**Issue by JSBoey** [datacarpentry/genomics-r-intro#120]
Hi! There seems to be missing clarification for episode 3 about the use and importance of the sigil ($) for accessing column names in a data frame (line 213 in `03-basics-factors-dataframes.Rmd`). The document mentions "this will be important later" but provides no further context. Examples of places where `$` is used and contextual definition might be important:
 - Episode 2 (Bonus material): Accessing a vector within a named list: `snp_data$position`
 - Episode 3: Extracting a column: `alt_alleles <- subset$ALT`
 - Episode 7: Setting global chunk options by accessing a function: `knitr::opts_chunk$set`

Perhaps a statement explicitly defining its common use to be included episode 3: "The `$` is used to access or extract a column by their names in data frames and objects within named lists."

**Comment by naupaka** [comment]
Closed via #269
