### ISSUE TITLE
Data Visualization with ggplot2 objective: titles, subtitles, and fonts

### ISSUE THREAD

**Issue by anjalisilva** [datacarpentry/genomics-r-intro#122]
Dear lesson maintainers, 

As a part of my checkout process, I would like to contribute to this lesson. My suggestion relates to lesson on 'Data Visualization with ggplot2'. One of the objectives of this lesson states: 'Customize plot scales, titles, subtitles, themes, fonts, layout, and orientation'. However, I do not see some of these concepts covered. For title, subtitles and fonts, this may be introduced as follows: 

To add a main title, use ggtitle(). For all options, see `?ggplot2::ggtitle`

```
ggplot(data = variants, aes(x = POS, y = DP)) +
  geom_point() +
  ggtitle("Main title of the plot")
```

To add main and subtitle, you may use the labs():

```
ggplot(data = variants, aes(x = POS, y = DP)) +
  geom_point() +
  labs(title = "Main title of the plot",
          subtitle = "Subtitle title of the plot")
```

To change the default font format:

```
ggplot(data = variants, aes(x = POS, y = DP)) +
  geom_point() + 
  labs(title = "Main title of the plot",
  subtitle = "Subtitle title of the plot") +
  theme(text = element_text(size = 16,  family = "Comic Sans MS"))
```

I understand the contributing guidelines states "Our lessons already contain more material than we can cover in a typical workshop, so we are usually not looking for more concepts or tools to add to them". In that case, you may also modify the objective.  Thank you.

Best wishes,
Anjali (she/her)

**Comment by ahmedmoustafa** [comment]
Thank you, @anjalisilva 🙏 Examples for changing the title and font of the plot have been added to the lesson.
