### ISSUE TITLE
Add introductory/background episode for a 1-day workshop version of the R lessons

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [datacarpentry/genomics-r-intro#123]
When the R Genomics material is taught on its own, learners have no background information on the data set and its associated narrative. They may also not understand what a VCF file is. Materials from https://datacarpentry.org/organization-genomics/data/ and  https://datacarpentry.org/wrangling-genomics/04-variant_calling/index.html could be re-organized into an episode to provide some background in this lesson repository.

**Comment by ytakemon** [comment]
@JasonJWilliamsNY ,  I couldn't quite figure out how to add this lesson to the schedule on the main page (https://datacarpentry.org/genomics-r-intro/), could you assist with this? I think lesson should take about 15 mins to cover.

**Comment by JasonJWilliamsNY** [comment]
@ytakemon let me look into that this weekend. Thanks!

**Comment by JasonJWilliamsNY** [comment]
@ytakemon somehow after running `make lesson-check` things seem to have worked and this is now live. Thanks!
