### ISSUE TITLE
Add Setup information

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/genomics-r-intro#13]
Setup information should NOT be listed in individual lesson repos, but should point back to the overall workshop setup page. 

- [ ] Add any setup info that is specific to this lesson to the overall workshop setup page
- [ ] Add text that points learners from this setup page to overall workshop setup page

**Comment by jananiravi** [comment]
@ErinBecker I'm not able to access this: https://datacarpentry.org/genomics-workshop/setup/ Is it because I don't have the right permission to? thanks!

**Comment by maneesha** [comment]
Looks like the link is not correctly formatted.
It works if you go to https://datacarpentry.org/genomics-workshop/setup.html

@jananiravi  Where do you see the link as you have it?

**Comment by jananiravi** [comment]
@ErinBecker sent me a similar one without the html. I updated the 01 intro lesson accordingly. thanks, Maneesha.

**Comment by JasonJWilliamsNY** [comment]
Update; to do - Delete the current setup instructions for R lessons and add instructions for installing R and RStudio
