### ISSUE TITLE
Remove setwd() in favor of Rproj

### ISSUE THREAD

**Issue by sstevens2** [datacarpentry/genomics-r-intro#144]
I saw the discussion of setwd in issue #15 and would like to bring this up for discussion again.  I feel like we should add a bit more to the section about creating a project about *why* you should create a project - for example that it sets your working directory which is great for a self contained project that is reusable by others.  Then we could remove the section teaching `setwd()` and instead leave a callout that says, sometimes you might see other people or their scripts setting their working directory directly but best practice is to use an Rproj instead.

**Comment by jananiravi** [comment]
A huge upvote, for what it's worth! 👍🏼 
This brings Jenny Bryan's post to mind: https://www.tidyverse.org/blog/2017/12/workflow-vs-script 💻 🔥
