### ISSUE TITLE
vcf.csv file for Data Analysis and Visualization

### ISSUE THREAD

**Issue by sohyunbk** [datacarpentry/genomics-r-intro#146]
The half of the episodes in [Data Analysis and Visualization in R](https://datacarpentry.org/genomics-r-intro/), requires "/home/dcuser/r_data/combined_tidy_vcf.csv" file for variants object.
Some people might not have the file if they did not perform analysis from the previous lesson, but want to learn data analysis in R.
It would be great if we connect the link to download the vcf.csv file in https://datacarpentry.org/genomics-r-intro/03-basics-factors-dataframes/index.html page.

**Comment by naupaka** [comment]
It is available here: https://github.com/datacarpentry/genomics-r-intro/tree/main/data

But I agree it would be nice to have a link to download it if they don't have it from previous episodes.

**Comment by naupaka** [comment]
This has now been addressed in the lesson. Thanks!
