### ISSUE TITLE
Where is bioconductor vcfR used in the lesson?

### ISSUE THREAD

**Issue by kerchner** [datacarpentry/genomics-r-intro#147]
I just want to make sure I'm reading the lesson materials correctly.  In "Using packages from Bioconductor", students install the vcfR package from Bioconductor.   Is there any part of the lesson after this point where students use functions from vcfR?  Or is the point of this section mainly to just show how one would install packages from Bioconductor if one were going to use them?

**Comment by naupaka** [comment]
The script that takes the vcf files and tidies them for the data viz lesson uses `vcfR`. There was intent at one point to demonstrate a few of the simple plotting functions that the `vcfR` package makes available, but they may not yet be added in.

**Comment by naupaka** [comment]
Closing this as the current scope of the lesson is just to show people how to install a package from Bioconductor. In the future we may add more content on this topic.
