### ISSUE TITLE
Do we need to use setwd()?

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/genomics-r-intro#15]
[The first episode](https://carpentrieslab.github.io/genomics-r-intro/01-introduction/index.html) has learners using setwd() and then tells them never to use setwd(). Do they need to use setwd() if they've already set up a project?

**Comment by naupaka** [comment]
No! If you use `setwd()` Jenny Bryan will set your computer on fire! :)

We should remove that.

https://www.tidyverse.org/articles/2017/12/workflow-vs-script/

**Comment by JasonJWilliamsNY** [comment]
Kids will find out about `setwd()` and I'd rather they find out from us. 

The point here was to show that the command exists but explain that you generally will not want to use it, so in context I hope that it actually is trying to make a more memorable point.
