### ISSUE TITLE
part of speech analogy confusing for non-English primary language speakers

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/genomics-r-intro#16]
The section "Understanding object data types (modes)" in the [second episode](https://carpentrieslab.github.io/genomics-r-intro/02-r-basics/index.html) includes an extended analogy comparing R data types to parts of speech, using examples in English. I think this is a good analogy, but don't like the use of "jejune" and "Tuatara" as examples. Making these common words will make this analogy more relatable for learners who have languages other than English as their primary language. 

Possible changes:
- "jejune" --> common, slow . . . 
- "Tuatara" --> chair, table, shoe . . .

**Comment by naupaka** [comment]
I agree and like 'common' -> 'commonly' and 'chair' -> 'chairs'

**Comment by JasonJWilliamsNY** [comment]
Made obsolete by current version of lesson
