### ISSUE TITLE
"Magic of programming" tip is LOOOOONG

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/genomics-r-intro#17]
The [second episode](https://carpentrieslab.github.io/genomics-r-intro/02-r-basics/index.html) includes a tip box called "magic of programming". This tip box is long and complex. I understand the rationale behind including it, but I would recommend the Maintainers make a decision about whether this material is important or not. If it is important, and Instructors should cover it, let's put it in the main body of the lesson. If not, let's get rid of it.

**Comment by naupaka** [comment]
That seems reasonable to me. It's plenty of material as is, esp for just one day.
