### ISSUE TITLE
Get rid of lists material?

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/genomics-r-intro#18]
The end of [episode 2](https://carpentrieslab.github.io/genomics-r-intro/02-r-basics/index.html) includes a section on lists that is prefaced by "we're not going to use lists" in this lesson. I recommend removing this section to avoid the extra cognitive load.

**Comment by naupaka** [comment]
Seems reasonable to me. It's just a very small section. Or, it could be moved to a callout in the data frames lesson and we could make the point that data frames are lists.
