### ISSUE TITLE
Merge into main, not into gh-pages 

### ISSUE THREAD

**Issue by julianstanley** [datacarpentry/genomics-r-intro#191]
https://github.com/datacarpentry/genomics-r-intro/blob/5084e86ad14cfba3065ee873b55d6317c2194c39/CONTRIBUTING.md?plain=1#L112

The above line in _Contributing_ states that PRs should come from branches originating from `gh-pages`, but I think (looking at commit history on this repo) that branches are being merged into `master` instead, right?

**Comment by naupaka** [comment]
It's actually 'main' now. Definitely not gh-pages. A PR to make that revision would be welcome.

**Comment by julianstanley** [comment]
Okiedoke, thanks!

**Comment by naupaka** [comment]
Closed via #193
