### ISSUE TITLE
Reports with knitr - consider recommending package tinytex for PDF reports

### ISSUE THREAD

**Issue by CarolynKoehn** [datacarpentry/genomics-r-intro#194]
In the "Producing Reports with knitr" lesson (https://datacarpentry.org/genomics-r-intro/07-knitr-markdown/index.html), the tip for creating PDFs provides links to install MiKTeX/MacTeX. I'd suggest that a more R-user-friendly option would be to install the tinytex package (https://yihui.org/tinytex/) and run all installations of TeX from R.

Example of tip box edit:
Tip: Creating PDF documents

Creating .pdf documents may require installation of some extra software. If required this is detailed in an error message.

To install the required software to knit your report to a PDF, you can run the following code:
> install.packages('tinytex')
> tinytex::install_tinytex()

**Comment by naupaka** [comment]
I think this is probably a reasonable suggestion, if for no other reason than that a full TeX install would use up a lot of bandwidth if folks tried to do it during a workshop on shared WiFi.

**Comment by naupaka** [comment]
@CarolynKoehn I'd welcome a PR making an adjustment to this tip

**Comment by naupaka** [comment]
Thanks! I'll take a look. For context, PR is #195

**Comment by naupaka** [comment]
Closed by #195
