### ISSUE TITLE
Tracking PR #79 : Changing ggplot jitter use and adding boxplots + Travis CI issue

### ISSUE THREAD

**Issue by ytakemon** [datacarpentry/genomics-r-intro#198]
Given the upcoming changes in infrastructure, we are closing PR #79 and will return to apply these changes in the new lesson structure.

**Comment by naupaka** [comment]
This is a good change that I think we should merge. I will need to cherry-pick the commit and submit in a new PR against the new main branch.

**Comment by naupaka** [comment]
Closing as the lesson has been substantially revised and this issue is now resolved in the new materials.
