### ISSUE TITLE
Add intro to MarkDown on Episode 01.

### ISSUE THREAD

**Issue by javibio-git** [datacarpentry/genomics-r-intro#203]
I think this episode should introduce learners to MarkDown as well. The idea is to make learners aware that Rscripts are not the only way to write  R code in Rstudio. Thus, this episode could direct learners to the [MarkDown](https://carpentries-incubator.github.io/markdown-intro/index.html) if they want to know more.

**Comment by naupaka** [comment]
Closing since we decided to remove the knitr episode from this lesson. Markdown is definitely very useful, but we are working to be mindful of the amount of material that already needs to be covered.
