### ISSUE TITLE
Should this lesson should be labeled as beta?

### ISSUE THREAD

**Issue by sstevens2** [datacarpentry/genomics-r-intro#207]
It seems there have been beta pilots #142 for this lesson and it has been taught quite a bit, I've taught it at least 3 times over 3 years.  I recommend it be moved to "beta" in the lifecycle that fits the [lesson lifecycle documentation](https://cdh.carpentries.org/the-lesson-life-cycle.html#polishing-beta-stage)

Also this relates to an [issue on the full workshop lesson page ](https://github.com/datacarpentry/genomics-workshop/issues/137) as there is a warning on the index page there.

**Comment by ytakemon** [comment]
Hi @sstevens2, we have field tested this workshop with one group last fall and were looking for another group to test this, as a part of the "Field testing: alpha stage" of the lesson lifecycle. Since you've taught this a few times now, I wonder if you could provide us with some feedback/notes as our "second" tester? Can you share your thoughts on this @ErinBecker? 

We have our monthly maintainers call this morning so I will bring this up with the group as well.

**Comment by sstevens2** [comment]
I'd be happy to share the sticky note feedback.  Something odd happened in 2020 but I have feedback from 2019, 2021, and 2022.  We will run it again in Aug 2023 as well.  Is there someone in particular I should add to be able see the feedback in google sheets?

**Comment by JCSzamosi** [comment]
Just commenting to get updates

**Comment by ytakemon** [comment]
Hi - sorry for the delay in following up. We need two official beta-test workshops to move our lesson to the beta life cycle, and we'll have our final one next month. Once changes have been implemented from their comments, we will update the lesson life cycle status. 

Sarah, I'm also happy to take a look at the feedback you got to see if we can address them, along with other changes we are currently making to the lesson. I think you already have my email, so feel free to add me to the google sheet.

**Comment by JCSzamosi** [comment]
Sorry, I should have been clear. I wasn't trying to bug anyone for updates, I just wanted to make sure I would receive notifications from github when there was movement on this thread, because I didn't want to subscribe to the whole repo

**Comment by ErinBecker** [comment]
Sorry for the delay on this. Yes, this lesson should be marked as "beta" while it is in the beta piloting stage. After beta pilots are complete and feedback from those pilots has been incorporated it will be ready to progress to "stable" (pending approval from the @datacarpentry/curriculum-advisors-genomics
