### ISSUE TITLE
Suggestion to update package cache

### ISSUE THREAD

**Issue by zkamvar** [datacarpentry/genomics-r-intro#217]
On 2023-06-06, this lesson was supposed to receive an automated pull request that updated the packages used in this lesson so that you could inspect the changes. Due to an upstream change in the Posit Package Manager URL, this did not happen because the GitHub Action that would create the pull request halted.

This action will run again on 2023-07-04, but **if you want to run it earlier**, you
should be able to go to the Actions tab and [manually run](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow?tool=webui) The `03 Maintain: Update Package Cache` workflow. 

One of the promises of The Workbench is that the setup is reliable and there are no surprises when it comes to building lessons that use R Markdown. The package cache ensures reproducibility, but because the lessons need to move with the flow of the R ecosystem, we built in a way to update the packages automatically via pull request. These pull requests will happen every month on the first Tuesday of the month and will only update components inside the `renv/` folder of your lesson. This will trigger a rebuild of all the episodes of your lesson so that you can detect instances where outputs have changed because of the new package versions.

**Comment by naupaka** [comment]
I just manually triggered the workflow and will review the changes.

**Comment by naupaka** [comment]
@zkamvar thanks for the note about this. I just tried to run it manually but it failed with an error:

<img width="732" alt="CleanShot 2023-09-13 at 08 58 10@2x" src="https://github.com/datacarpentry/genomics-r-intro/assets/1428071/9f069975-85b7-4d8d-ac1f-8247285fc622">

https://github.com/datacarpentry/genomics-r-intro/actions/runs/6174719030/job/16759947946#step:4:488

I am not sure what precisely is going wrong and how to resolve it. Any ideas?

**Comment by zkamvar** [comment]
The packages have been updated in https://github.com/datacarpentry/genomics-r-intro/pull/226, and I forgot to link this issue. 

In general if a workflow fails, it's my fault and you shouldn't have to worry about it (except for notifying me). I believe this can be safely ignored, but I am running a new one and will monitor it.

I believe the issue is that {renv} changed the behaviour of what we use to update packages when no updates are available. I will investigate this, but again, this issue is resolved by https://github.com/datacarpentry/genomics-r-intro/pull/226
