### ISSUE TITLE
remove section on read.xlsx

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/genomics-r-intro#22]
From @naupaka:
> The only substantive suggestion I had is about removing the xlsx metadata file and just using a csv and read.csv() instead. It's an additional dependency to use readr and I really don't think we should have folks using that format if possible... for a bunch of reasons including the binary format precluding both the full use of git and the use of bash tools to parse.

See https://github.com/carpentrieslab/genomics-r-intro/pull/19

**Comment by ErinBecker** [comment]
@JasonJWilliamsNY for feedback

**Comment by JasonJWilliamsNY** [comment]
There aren't additional dependencies for our install - I think knowing about the excel import is such a win for people nervous to get started with R. It's such a basic thing to stumble at, if people get this to work, they can later get more comfortable with read functions. Also many people will have Excel data they want to bring in.

**Comment by JasonJWilliamsNY** [comment]
It was decided to keep this.
