### ISSUE TITLE
ggplot episode cleanup

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/genomics-r-intro#24]
The major bit of work that needs to be done before the alpha release is around cleaning up the ggplot episode. There are some code chunks and one or two exercises that integrate the vcf dataset, but I haven't had much luck in transitioning the rest of the code and exercises away from the metadata dataset. So this episode currently does not render. This is the biggest bit of work that needs doing before the lesson is teachable.

**Comment by ErinBecker** [comment]
@naupaka - would you be able to help out here? I'm not familiar with the vcf format and what all of the variables indicate, so haven't been able to come up with good examples.

**Comment by naupaka** [comment]
Sure, but not till the weekend at the soonest.

**Comment by ErinBecker** [comment]
Thanks @naupaka, that's perfect. If you get the time to do some work on this this weekend or so, please don't worry about all the formatting and such. Even if you could give me a list of appropriate visualizations to create, that would be a real big help. I could take it from there and get those incorporated into the lesson.

**Comment by ErinBecker** [comment]
Hey @naupaka - just a heads up that @ryanpeek was able to help me come up with appropriate visualizations for this data. I've put in a PR using his suggestions at #26. Review would be greatly appreciated!

**Comment by ErinBecker** [comment]
Closed with #26
