### ISSUE TITLE
Notice: this repository has moved 

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/genomics-r-intro#25]
As we are nearing the alpha release of this lesson, it has been transfered from `carpentrieslab` to the `datacarpentry` GitHub organization. While GitHub will redirect automatically, I encourage you to update the URL of your remotes:

```bash
git remote set-url <name-of-your-remote> git@github.com:datacarpentry/genomics-r-intro.git
```

The lesson is now rendered at: <https://datacarpentry.org/genomics-r-intro>

Please open an issue if you notice anything broken with the deployment/travis.

**Comment by ErinBecker** [comment]
Thanks @fmichonneau. Should we archive the carpentrieslab repo?

**Comment by fmichonneau** [comment]
no need to, the repository is transferred so there is no trace of it left at carpentrieslab!

**Comment by ErinBecker** [comment]
Excellent, thanks @fmichonneau!
