### ISSUE TITLE
Episode 4 - too few questions/challenges

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [datacarpentry/genomics-r-intro#32]
I like to have several challenges for each topic introduced if possible. One does not have to do them all but right now the entire episode only has 2. Also the `split-apply-combine` challenge and explanation is not built up piece by piece, so I think we could elaborate.

**Comment by JasonJWilliamsNY** [comment]
This lesson should end with some actual questions. Right now the examples show how dplyr functions work, but we don't seem to be going anywhere with a purpose.

**Comment by JasonJWilliamsNY** [comment]
I leave to @ytakemon and the maintainer group to discuss and decide if we now have enough example questions. Looking much better.

**Comment by ytakemon** [comment]
`Split-apply-combine` section has been updated in #108. It now includes a question/challenge at the end.
