### ISSUE TITLE
02-r-basics: Order of solutions in "Exercise: Create objects and check their modes" is wrong

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [datacarpentry/genomics-r-intro#39]
The order of the solutions is incorrect

**Comment by JasonJWilliamsNY** [comment]
Fixed in current lesson, but for some reason there is an additional error message displayed in the lesson evaluation on the site build. I'll see if I can remove that to make things a bit cleaner.

**Comment by naupaka** [comment]
The error happens because the assignment fails for the object that doesn't exist. Not sure how you'd get rid of it?

**Comment by naupaka** [comment]
Thanks @JasonJWilliamsNY
