### ISSUE TITLE
02-r-basics: Formatting issue in "Exercise: Examining and subsetting vectors"

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [datacarpentry/genomics-r-intro#40]
Check the formatting - there is a line break missing in list of questions. Should check all exercise formatting.

**Comment by Sailendharan** [comment]
I checked the whole lesson, review exercise 1 and review exercise 2 are the other ones I found to have line breaks missing between the questions and choices.

**Comment by naupaka** [comment]
Resolved in current version of lesson
