### ISSUE TITLE
03-basics-factors-dataframes: Importing data from Excel example is broken

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [datacarpentry/genomics-r-intro#41]
This example and screenshots uses the older Ecoli submission metadata. Once a choice is made, the example should be updated.

**Comment by ewallace** [comment]
Request, maybe for @JasonJWilliamsNY or @ErinBecker: could you post a link to `Ecoli_metadata.xlsx` here if possible? We are hoping to teach this lesson real soon.

Long-term request: could you add `Ecoli_metadata.xlsx` to the figshare repo?

Apologies if this file was already on the figshare repo; @FlicAnderson and I thought we had looked.

**Comment by naupaka** [comment]
Updated in the current lessons. The xlsx file is committed into the repo here:
https://github.com/datacarpentry/genomics-r-intro/blob/main/_episodes_rmd/Ecoli_metadata.xlsx
