### ISSUE TITLE
05-data-visualization: loading ggplot2 starts with an error in the lesson page

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [datacarpentry/genomics-r-intro#43]
Should fix!

**Comment by gosianow** [comment]
+1 
We would like to use that lesson at the beginning of July. Do you think you would be able to have it fixed by then? Many thanks

**Comment by fmichonneau** [comment]
this turned out to be a bug in the package we use to detect lesson dependencies. The fix here is a workaround
