### ISSUE TITLE
05-data-visualization - This lesson is pre-alpha

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [datacarpentry/genomics-r-intro#44]
We don't have valid outputs or images... objectives and questions are not clearly laid out. This lesson is not yet at the alpha stage!

**Comment by JasonJWilliamsNY** [comment]
There is no narrative on what we are plotting and why

**Comment by ewallace** [comment]
I've tried to address this in #95, and taught the lesson. I hope this brings it up at least to alpha, maybe to beta level? Feedback welcome.

**Comment by naupaka** [comment]
@ahmedmoustafa can you review-self assign?

**Comment by naupaka** [comment]
This is now addressed with the new version of the materials.
