### ISSUE TITLE
XX-knitr-markdown: link/credit to existing lesson

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [datacarpentry/genomics-r-intro#46]
This content seems to have been copied from
http://kbroman.org/datacarpentry_R_2018-01-08/04-rmarkdown.html

I don't see any attribution or know what's up with this.

**Comment by jananiravi** [comment]
Yeah, just noticed it when I came across `Karl Broman` listed in the text. 🤔 
Is the outline going to be revised to specifically output the workflow for the preceding genomics lesson? Or is this to serve as a general intro to `RMarkdown` to supplement the cheatsheet?

**Comment by naupaka** [comment]
Hopefully this will be addressed by @kpoterlowicz's revision of the knitr episode.

**Comment by naupaka** [comment]
We removed the knitr/rmarkdown episode from the lesson so this is no longer needed
