### ISSUE TITLE
XX-knitr-markdown: This lesson is pre-alpha

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [datacarpentry/genomics-r-intro#47]
This lesson does not tie back to the rest of the genomics content/examples.

**Comment by naupaka** [comment]
Hopefully this will be addressed by @kpoterlowicz's revision of the knitr episode.

**Comment by naupaka** [comment]
@tracykteal here's the issue regarding the knitr lesson.

The existing lesson it comes from is here: https://ucsbcarpentry.github.io/2019-04-11-UCSB-SW-Workshop/r-novice/15-knitr-markdown/index.html (see also https://github.com/datacarpentry/genomics-r-intro/issues/46 )

**Comment by naupaka** [comment]
Closed via #210
