### ISSUE TITLE
Episode 05 (Data Visualization): geom_jitter()

### ISSUE THREAD

**Issue by jessepharrison** [datacarpentry/genomics-r-intro#62]
Reading through the ggplot2 section, I feel this part could be clarified:

_Notice that we can change the geom layer and colors will be still determined by sample_id_

```
ggplot(data = variants, aes(x = POS, y = DP, color = sample_id)) + 
  geom_jitter(alpha = 0.5)
```

Previous parts of the lesson involve using `geom_point()` and the difference between that vs. `geom_jitter()` is not described, apart from stating that we're changing the geom layer. This could be confusing since the two plots look very similar and one has to look quite closely to notice the differences. 

To make this easier to follow, one could explain that `geom_jitter()`:

- produces a scatter plot that adds some random variation to the position of each point
- functions as a shortcut for `geom_point(position = "jitter")`
- is likely to be useful in situations where overplotting is an issue

This would also help illustrate why, in the case of the example data, we don't see that much of a difference in the output (a regular scatter plot already seems to represent the data quite well).

**Comment by naupaka** [comment]
@ahmedmoustafa can you review-self assign?

**Comment by naupaka** [comment]
Closing as this has been addressed in the new, substantially revised data viz episode.
