### ISSUE TITLE
lesson contribution [submitted by email]

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/genomics-r-intro#70]
For the lesson contribution component of the checkout, I will be focusing on the Intro to R and Rstudio for Genomics lesson (found here: https://datacarpentry.org/genomics-r-intro/). Specifically I will be focusing my contributions on the Producing Reports With knitr (https://datacarpentry.org/genomics-r-intro/XX-knitr-markdown/index.html).

I love the lesson - it does a great job of stressing reproducibility and how that can be achieved via a self-contained document. Because producing R markdown documents and R markdown presentations follows the same general syntax, I think that in the last section, we can add additional information on producing R markdown slides. Since the "What not to contribute" Page in the Contributing.MD file encourages not to add more concepts, I believe the easiest way to add this would be to briefly mention this in the final section, incorporate it as a challenge for students to explore, and add more links in the "Resources" section for them to explore rather than add a whole new e. That way it only adds 2-3 min or so to the lesson plan, and allows learners to explore other powerful tools made accessible by the skills they just learned in this lesson.

See the proposed contribution below in brown:

--------------------------------------------------------------------------------------------------------------
Other output options
You can also convert R Markdown to a PDF or a Word document. Click the little triangle next to the "Knit HTML" button to get a drop-down menu. Or you could put pdf_document or word_document in the header of the file.

Furthermore, now that you have learned about creating R Markdown documents, we will briefly mention other options outside the scope of this lesson that are now readily accessible to you with the skills you have just acquired.

R Markdown is also flexible enough to produce reproducible reports in the form of a presentation, which offers users an alternative format to present results if you are reviewing them at a meeting or in a presentation/lecture setting. T

To access this, within R Studio, click File → New File → R Markdown and you'll get a dialog box like this:
image.png
Click "Presentation" on the left column, select HTML (ioslides_presentation), and you will see the same general markdown syntax as before,

image.png
except now when you click "knit", you'll see an R markdown slideshow presentation as compared to an R Markdown document.

Challenge
Integrate any one of the previous challenges into an R markdown presentation.
Resources
...
https://rmarkdown.rstudio.com/lesson-11.html
https://rmarkdown.rstudio.com/gallery.html (scroll down to Presentations)
--------------------------------------------------------------------------------------------------------------

**Comment by naupaka** [comment]
@kpoterlowicz can you take a look and see if this can/should be incorporated into the knitr lesson?
