### ISSUE TITLE
Complete a few missing pieces for Lesson "Data Visualization with ggplot2"

### ISSUE THREAD

**Issue by yuanxiesa** [datacarpentry/genomics-r-intro#73]
Hello,

As a part of my checkout process, I would like to contribute to this lesson. Since the "question" part is still blank, I formulated a few and supplied my own answers. I think those are very important concept in understanding ggplot. You are welcome to incorporate those answers into the course materials, adding it anywhere you see fit.

Below is my contribution. 

Questions
1. What is the grammar of graphics (gg)? How does that concept guide the way the ggplot2 package creates graphics?
2. What is mapping, and what is aesthetics?
3. What is the process of creating a plot with ggplot in R?

Answers

The “gg” in “ggplot” stands for “grammar of graphics,” which is an elegant yet powerful way to describe the making of scientific plots. In short, the grammar of graphics breaks down every plot to a few components, namely, a dataset, a set of geoms (visual marks that represent the data points), and a coordinate system. You can imagine this is a grammar that gives unique names to each component appearing in a plot and conveys specific information about data. With ggplot, graphics are built step by step by adding new elements.

`summary(mpg)`

The idea of “mapping” is crucial in ggplot. One familiar example is to “map” the value of one variable in a dataset to x and the other to y. However, we often encounter datasets that include multiple variables. In this case, ggplot allows you to “map” those other variables to visual marks such as color, shape, or line type (called aesthetics or aes). One thing you may want to remember is the difference between discrete and continuous variables. Some aesthetics, such as the shape of dots, do not accept continuous variables. If forced to do so, R will give an error. This is easy to understand; we cannot create a continuum of shapes for a variable, unlike, say color.
When having doubts about whether a variable is continuous or discrete, a quick way to check is to use the summary function. Continuous variables have descriptive statistics but not the discrete variables.

-------------------------------------------------------------------------------------------------------------

I will contribute more to this lesson in the future.

Best wishes,
Yuanxi

**Comment by NadineBestard** [comment]
Hi, 
I do not know if this issue is trying to adress the same: In overview the "Question" part is missing. But this is just where the Objectives should be adress in form of a question to catch the learner interest.
The key points are also missing.

**Comment by ewallace** [comment]
I've tried to address some of these in pull request #95, and would appreciate feedback on that.

**Comment by ytakemon** [comment]
@ahmedmoustafa can you review-self assign?

**Comment by ahmedmoustafa** [comment]
Thank you so much @yuanxiesa! Your contribution has been [integrated into the lesson](https://datacarpentry.org/genomics-r-intro/06-data-visualization).
