### ISSUE TITLE
Add 'citations' and 'bibliography' subject to Producing Reports episode

### ISSUE THREAD

**Issue by timcashion** [datacarpentry/genomics-r-intro#74]
Something I've found very helpful for my own report writing in RMarkdown is the use of references directly in the report. I find this makes it easier to convert these directly to reports/scientific manuscripts or to document the sources of your data and methods. 

Here's a rough sketch of how I think this could be included: 

**In-Text Citations and Bibliography**
One other helpful addition available in RMarkdown is the inclusion of in-text citations and bibliographies. This happens in a number of steps. The first is in modifying the YAML section at the top of your RMarkdown document. 

*YAML*
First, you'll want to add a file that references your bibliography at the top of your RMarkdown document in the YAML section. The easiest way to generate one of these files is from an existing reference management software where you can export the library as a .bib file or .ris file. Here, I've exported a file called MyCollection.bib which is in the same directory as my .Rmd file. 

`
---
title: "Initial R Markdown document"
author: "Karl Broman"
date: "April 23, 2015"
output: html_document
bibliography: MyCollection.bib
---
`

*In-Text Citations*
If you want to place in-text citations write '[@CitationKey]' where you would like it to be placed in your text. The format of your citation key is dependent on your reference management software that you are using to organize your .bib file (e.g., Mendeley, Zotero, Papers, etc.). If you would like to exclude the Author from this citation (i.e., only display the year), you can put a '-' sign before the '@' symbol (e.g., '[-@CitationKey]')

*Bibliography/References*
By default, the references cited in-text will be added at the bottom of your knitted document. 

*Challenge*
Add a bibliography to the Rmarkdown report you are working on with at least one in-text citation.

**Comment by naupaka** [comment]
Closing this as we have decided to remove the knitr episode from this lesson altogether due to the time constraints in a single workshop.
