### ISSUE TITLE
Typo in diagram of RStudio panel layout

### ISSUE THREAD

**Issue by jrmuirhead** [datacarpentry/genomics-r-intro#75]
There's a typo in the figure for the R layout that occurs just after the 
heading Overview and customization of the RStudio layout
in datacarpentry/genomics-r-intro/_episodes_rmd/01-introduction.Rmd.

Environment is spelled wrong in the figure.

The file is located at "/fig/rstudio_session_4pane_layout.png. This is a straight-forward fix, and I would be happy to produce a corrected diagram.

<img width="1589" alt="rstudio_session_4pane_layout" src="https://user-images.githubusercontent.com/22942232/80750897-e4985d80-8af6-11ea-8578-cb1a4484c952.png">

**Comment by ytakemon** [comment]
Thanks for noticing the typo, @jrmuirhead! I will fix add a fix to this in the next few days.
