### ISSUE TITLE
use read_csv instead of read.csv

### ISSUE THREAD

**Issue by maglet** [datacarpentry/genomics-r-intro#85]
As referenced in #66 i think we should replace read.csv with read_csv to get into tibbles right away

This will eliminate the need for head because tibbles only display 10 lines in the output

I find learners are ok with the explanation that tibbles work mostly the same as data frames, but we can have an aside with more detail

**Comment by ytakemon** [comment]
Hello @maglet - Thank you for this input. We will be working to transition the whole lesson towards using Tidyverse terminology moving forward and so this will be addressed in the very near future. Cheers

**Comment by jananiravi** [comment]
Sounds good -- I am happy to help with transitioning to tidyverse, @ytakemon.

**Comment by ytakemon** [comment]
This is now addressed in a recent transition to using tidy-centric functions in a recent pull request #96
