### ISSUE TITLE
Interested in helping shape R-genomics?

### ISSUE THREAD

**Issue by naupaka** [datacarpentry/genomics-r-intro#89]
These lessons are still in alpha and are being actively developed. Since things are still in a state of flux, we don't have specific issues that need help at the moment, but if you are interested in participating, comment on this issue.

**Comment by ewallace** [comment]
Hi! I'm interested in helping. We are teaching using some of this material [in Edinburgh over the next couple of weeks](https://edcarp.github.io/2020-12-01-edinburgh-bio-online/). We [forked the material to put some Edinburgh-specific information such as our local RStudio server](https://github.com/edcarp/genomics-r-intro).

I'm particularly interested in helping with the ggplot material, as I will be adding to that to teach next week anyway, and I delivered some more R material based on this a while ago. Is there a roadmap for the ggplot2 lesson, or who should I talk to about it?

Thanks all for putting this great resource together!

**Comment by naupaka** [comment]
@ewallace thanks for your interest! We're making slow and steady progress getting these polished. We'll get some more details posted soon here on GH.

**Comment by yonathantilahun** [comment]
Will you be producing any lessons on using Qiime2? If so I would like to contribute to the lesson on using R and R-studio for Qiime2.

**Comment by jananiravi** [comment]
@naupaka I'm interested in contributing, especially with integrating tidyverse with the genomics lessons.

**Comment by naupaka** [comment]
@yonathantilahun no plans to incorporate QIIME at this time, unfortunately.

@jananiravi great! We're working through the alpha version, but once we get that in place I'm sure there will be lots of ways to plug in to the development.

**Comment by mxiang128** [comment]
Hi, I'd like to contribute to content related to RNA sequencing (bulk, single-cell), statistics and data visualization (ggplot2). The current genomics curriculum is a good start but needs additional lessons in quantitative and comparative analysis to make it more complete.

**Comment by naupaka** [comment]
@chechoid thanks for the interest! The lessons are almost ready for a beta release, and at that point we'll have a number of issues needing attention.

**Comment by chechoid** [comment]
ok @naupaka, that's great news! I cheris this lesson because it's the one I used for my Data Carpentry certification, so I'll do everything I can to develop it.

**Comment by ntsotakos** [comment]
Hi @naupaka, how close are these lessons to the beta release? I had my Instructor Training recently, and I currently teach Bioinformatics, so I am willing to help any way I can (and can field test in my class).

**Comment by naupaka** [comment]
@ntsotakos I believe the next formal step is for them to be piloted with one or more of the maintainers in attendance, then any revisions made, etc. The maintainers are working on adding content to the knitr and ggplot lessons at the moment. If you look through the lessons as they are and add any issues you spot, that would likely be helpful and we work though this phase!

**Comment by naupaka** [comment]
It's mostly through the beta phase; been piloted formally once and they're aiming for another one soonish. We're in the midst of a big overhaul (see #142) so perhaps it would be easiest (e.g. to avoid merge conflicts) to hold off on any PRs for now. General issues or suggestions are always welcome though!

**Comment by naupaka** [comment]
Yes those are the files. You can also check the rendered version [datacarpentry.org/genomics-r-intro/](https://datacarpentry.org/genomics-r-intro/)

**Comment by vhmcck** [comment]
Hi @naupaka, 

First of all, congratulations! A beautiful lesson, with heaps of content - the challenge will be covering as much as possible in the allocated time, as usual. My comments on the [Producing Reports With knitr](https://datacarpentry.org/genomics-r-intro/07-knitr-markdown/index.html#overview) episode are below.

- It would be good to provide further information on what Markdown is when defined under [Literate programming](https://datacarpentry.org/genomics-r-intro/07-knitr-markdown/index.html#literate-programming). I suggest [The Markdown Guide](https://www.markdownguide.org/).

- Missing image of the dialog box under [Creating an R Markdown file](https://datacarpentry.org/genomics-r-intro/07-knitr-markdown/index.html#creating-an-r-markdown-file).

- I could not find the Markdown Quick Reference - there is no "little question mark" next to "Knit HTML" in my version of R studio (2022.02.3).

- The example for section headers is missing how these should look like. The same applies to the examples for hyperlinks, images, subscripts, and equations later on.

- For images under [A bit more Markdown](https://datacarpentry.org/genomics-r-intro/07-knitr-markdown/index.html#a-bit-more-markdown), learners may need instructions on how to get URLs for images created in a local environment (e.g., their Desktop folder).

- It would be useful to provide a link to the [documentation](http://rmarkdown.rstudio.com) when introducing R Markdown under [R code chunks](https://datacarpentry.org/genomics-r-intro/07-knitr-markdown/index.html#r-code-chunks), so learners have it handy.

- The [How things get compiled](https://datacarpentry.org/genomics-r-intro/07-knitr-markdown/index.html#how-things-get-compiled) scheme may be misleading. After saving, I can only see the .Rmd and .html files - where should I find .md and figs/?

- The explanation for `fig.path` is not clear - what is the "standard place"?

- The challenge for [In-line R code](https://datacarpentry.org/genomics-r-intro/07-knitr-markdown/index.html#inline-r-code) (note the typo) is a bit too general. I suggest something along the lines: "Try out a bit of in-line R code by defining a variable "average" of the numbers from 0 to 10, inclusive. Then round the result to a _value_ with 3 decimals and show only this number after the sentence: 'The 0-10 average is _value_'".

- All challenges are missing solutions.

- The R Markdown cheat sheet (PDF) under [Resources](https://datacarpentry.org/genomics-r-intro/07-knitr-markdown/index.html#resources) does not work. I believe this is the one you are after:
https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf

- It would be great to add something about the Publish Document option and comment on (possibly additional?) packages/updates that R may need to operate knitr. I got a few new ones when playing with Markdown in my local environment.


I am interested in helping with the Beta release. I have used R to analyse microbiome data and produce publication-quality graphs. Please keep me in the loop!

Cheers,
Valentina

**Comment by naupaka** [comment]
@vhmcck thanks! This is great. Can I ask you to take the content you just posted and add it as a new issue on its own so we don't lose it here under the broader thread? Name it something like "Suggestions for improvements to the knitr lesson".

**Comment by vhmcck** [comment]
No worries, @naupaka. Happy to help! I just did it. Let me know if you see the issue.

**Comment by naupaka** [comment]
Thanks everyone for your help and suggestions -- I'm closing this issue for now but you should feel welcome to add new issues as you find them, or to help address existing issues with a PR.
