### ISSUE TITLE
Typo in "Introducing Factors" due to R 4.0.0

### ISSUE THREAD

**Issue by oliviaAB** [datacarpentry/genomics-r-intro#94]
Hi,

I don't think this has been reported before: due to the change to R 4.0.0, the function read.csv() now does not convert strings to factors. Therefore, is section 3: basic factors dataframe, in the paragraph Introducing Factors, the results of the commands don't match the text, i.e. variants$REF is not a factor anymore. Maybe the section about factors should be moved earlier, when introducing the other types of object.

**Comment by zkamvar** [comment]
Just popping in to add some extra information:

The changes due to R 4.0 can be found in #78 and we wrote some recommendations for migration earlier this year: https://carpentries.org/blog/2020/08/r-4-migration/

**Comment by ytakemon** [comment]
This has been fixed in a recent pull request #96
